Feature/tr 629 convert number line to standard ims compliant
oat-sa/extension-parcc-tei pull request #16
Opened 2021-05-11 06:19 UTC by btamas

2021-05-17 12:44 UTC, jsconan requested changes
This is a nice rework of the PCI. It works well both in CG and NG, with a freshly created item. However, it triggers a critical server error with items created before the update. The reason why is on the response declaration that is not changed for existing items.

I think it should be a breaking change, and the previous versions should not be removed while updating the PCI. Please see my comments below for more details.

2021-05-17 12:44 UTC, jsconan commented on views/js/pciCreator/ims/graphNumberLineInteraction/runtime/scss/graphNumberLineInteraction.scss
> +    border: 6px solid #f5f3f2;
**nitpick:** This color is used in several places, better to have it in a variable as well

2021-05-17 12:44 UTC, jsconan commented on views/js/pciCreator/ims/graphNumberLineInteraction/runtime/scss/graphNumberLineInteraction.scss
> +                background: #ddd;
**nitpick:** This should also go in a variable :)

2021-05-17 12:44 UTC, jsconan commented on views/js/pciCreator/ims/graphNumberLineInteraction/imsPciCreator.json
> +        "cardinality": "record"
**nitpick**: While this is ok to comply with what the PCI produces, it will introduce a severe issue once the platform gets updated with the version. The existing items will continue using the previous responseDeclaration, expecting a baseType integer, but the PCI will create a record and the Test Runner will stop on a critical error (`The value 'qtism\runtime\common\RecordContainer' is not compliant with the 'integer' baseType.`). It should require some additional change to update the response declaration as well.

Actually, the error is not directly produced by this exact change, but since you also fixed the produced response, it will fail for any existing item, unless something is made to fix them

Since it may be complex to update the response declaration, especially because it will require to save regenerate the existing items and tests, it might better to declare a breaking change, and do not remove the previous version of the PCI to keep existing tests working.

2021-05-17 12:44 UTC, jsconan commented on migrations/Version202105110950013025_parccTei.php
> +            $registry->removeAllVersions('graphNumberLineInteraction');
**thought:** I wonder if this should not be avoided. It will remove any previous version of the PCI, and therefore existing tests won't work anymore, unless they are rebuilt.

2021-05-18 11:32 UTC, marpesia commented
FYI
it's sending data correctly on the Test-taker view
![image (1)](https://user-images.githubusercontent.com/11692751/118643844-5bc19200-b7dd-11eb-9061-0b89f85eb7ba.png)

But it is not showing the answer correctly on the Response
![image](https://user-images.githubusercontent.com/11692751/118643910-73991600-b7dd-11eb-8cdd-a8c2c737ed12.png)

2021-05-18 14:07 UTC, btamas commented
> FYI
> it's sending data correctly on the Test-taker view
> 
> But it is not showing the answer correctly on the Response view

It is not the same, but it was working wrong in the previous version as well. I think the issue is on the Result page.
![Screen Shot 2021-05-18 at 16 06 16](https://user-images.githubusercontent.com/537151/118666084-2a53c100-b7f3-11eb-8d6a-5cf2022750bb.png)

2021-05-19 09:25 UTC, btamas commented on views/js/pciCreator/ims/graphNumberLineInteraction/imsPciCreator.json
> +        "cardinality": "record"
I created a task to update existing items: https://oat-sa.atlassian.net/browse/TR-1336

2021-05-20 05:56 UTC, marpesia approved these changes
I've tested on Current Gen and it goes well.
Nice job!

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-05-20 14:44 UTC, jsconan approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2023-04-12 10:22 UTC, closed without merging