Fix/tao 5747/response condition
oat-sa/extension-parcc-tei pull request #3
Opened 2017-12-28 09:25 UTC by zagovorichev

2017-12-29 08:46 UTC, krampstudio requested changes
This change fix the problem for all PCIs but the "Graphing f(x)" PCI. If you try to add the "Fractions" PCI remove it and add again the "Graphing f(x)" PCI, there's still an error `uncaught exception: unexpected number of rc found`

Also the rule is to do a check on the code style when opening very old files, like moving variable declaration to the top of their scope or throwing `new Error` instead of  [a string](https://github.com/oat-sa/extension-parcc-tei/pull/3/files#diff-41c1a3d631f67aa9568fccc12ce91c24R59)
It would be great if you can make those changes too.

2018-01-03 07:33 UTC, zagovorichev commented
@krampstudio Update

2018-01-03 07:59 UTC, zagovorichev commented on views/js/pciCreator/helper/responseCondition.js
> +            responseIdentifierCount : $respVar.length
Instead of this I could count all RESPONSE from template, of course if this has sense for you

2018-01-03 08:55 UTC, krampstudio approved these changes
It seems fixed now

2018-01-03 08:55 UTC, merged